### ISSUE TITLE
[Bug]: Custom token not generated 

### ISSUE THREAD

**Issue by Sadman25** [AsifArmanRahman/firebase-rest-api#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
-   OS: Windows 10
-   Python: 3.8.10
```

### What happened?

The method create_custom_token of Auth class is not generating token as it is supposed to, instead it is throwing value error of 'key is not a JWK object' .

### Code Snippet

```shell
from config import SERVICE_CONFIG
from firebase import initialize_app

app = initialize_app(SERVICE_CONFIG)
token = app.auth().create_custom_token("RandomString")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "NewFile.py", line 5, in <module>
    token = app.auth().create_custom_token("RandomString")
  File "D:\Asif\venv\lib\site-packages\firebase\auth\__init__.py", line 138, in create_custom_token
    return jwt.generate_jwt(payload, private_key, "RS256", exp)
  File "D:\Asif\venv\lib\site-packages\python_jwt\__init__.py", line 90, in generate_jwt
    token.add_signature(priv_key, protected=header)
  File "D:\Asif\venv\lib\site-packages\jwcrypto\jws.py", line 540, in add_signature
    sig = c.sign()
  File "D:\Asif\venv\lib\site-packages\jwcrypto\jws.py", line 149, in sign
    raise ValueError('key is not a JWK object')
ValueError: key is not a JWK object
```

**Comment by AsifArmanRahman** [comment]
Thank you for a detailed description of the bug. It should be solved in the next release.
